version: '3'
services:
    php-apache:
        image: php:7-apache
        ports:
            - 80:80
        volumes:
            - ./DocumentRoot:/var/www/html:z
        links:
            - 'mysql'

    mysql:
        image: mysql:5.6
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysqltester
        ports:
            - 3306:3306
